/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module apb(clk, reset_n, transfer, read_write, wr_addr, wr_data, rd_addr, rd_data, done);
  input clk;
  output done;
  wire [7:0] paddr;
  wire penable;
  wire [7:0] prdata;
  wire pready;
  wire psel;
  wire [7:0] pwdata;
  wire pwrite;
  input [7:0] rd_addr;
  output [7:0] rd_data;
  input read_write;
  input reset_n;
  input transfer;
  input [7:0] wr_addr;
  input [7:0] wr_data;
  apb_master master (
    .PADDR(paddr),
    .PCLK(clk),
    .PENABLE(penable),
    .PRDATA(prdata),
    .PREADY(pready),
    .PRESETn(reset_n),
    .PSEL(psel),
    .PWDATA(pwdata),
    .PWRITE(pwrite),
    .READ_WRITE(read_write),
    .done(done),
    .read_addr(rd_addr),
    .read_data(rd_data),
    .transfer(transfer),
    .write_addr(wr_addr),
    .write_data(wr_data)
  );
  apb_slave slave (
    .PADDR(paddr),
    .PCLK(clk),
    .PENABLE(penable),
    .PRDATA(prdata),
    .PREADY(pready),
    .PRESETn(reset_n),
    .PSEL(psel),
    .PWDATA(pwdata),
    .PWRITE(pwrite)
  );
endmodule

module apb_master(PCLK, PRESETn, transfer, READ_WRITE, write_addr, write_data, read_addr, read_data, done, PWRITE, PSEL, PENABLE, PADDR, PWDATA, PRDATA, PREADY);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire [7:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  output [7:0] PADDR;
  input PCLK;
  output PENABLE;
  input [7:0] PRDATA;
  input PREADY;
  input PRESETn;
  output PSEL;
  output [7:0] PWDATA;
  output PWRITE;
  input READ_WRITE;
  output done;
  wire [1:0] next_state;
  input [7:0] read_addr;
  output [7:0] read_data;
  wire [1:0] state;
  input transfer;
  input [7:0] write_addr;
  input [7:0] write_data;
  INV_X1 _055_ (
    .A(state[0]),
    .ZN(_020_)
  );
  INV_X1 _056_ (
    .A(state[1]),
    .ZN(_021_)
  );
  INV_X1 _057_ (
    .A(READ_WRITE),
    .ZN(_022_)
  );
  INV_X1 _058_ (
    .A(PSEL),
    .ZN(_023_)
  );
  INV_X1 _059_ (
    .A(PENABLE),
    .ZN(_024_)
  );
  NOR2_X1 _060_ (
    .A1(state[0]),
    .A2(state[1]),
    .ZN(_007_)
  );
  NAND2_X1 _061_ (
    .A1(transfer),
    .A2(_007_),
    .ZN(_008_)
  );
  NOR2_X1 _062_ (
    .A1(_020_),
    .A2(state[1]),
    .ZN(_009_)
  );
  OAI21_X1 _063_ (
    .A(_008_),
    .B1(_021_),
    .B2(_020_),
    .ZN(next_state[0])
  );
  OAI21_X1 _064_ (
    .A(_020_),
    .B1(_021_),
    .B2(PREADY),
    .ZN(next_state[1])
  );
  AND3_X1 _065_ (
    .A1(_020_),
    .A2(state[1]),
    .A3(PREADY),
    .ZN(_005_)
  );
  NAND4_X1 _066_ (
    .A1(_020_),
    .A2(state[1]),
    .A3(PREADY),
    .A4(READ_WRITE),
    .ZN(_010_)
  );
  MUX2_X1 _067_ (
    .A(PRDATA[6]),
    .B(read_data[6]),
    .S(_010_),
    .Z(_006_[6])
  );
  MUX2_X1 _068_ (
    .A(PRDATA[5]),
    .B(read_data[5]),
    .S(_010_),
    .Z(_006_[5])
  );
  MUX2_X1 _069_ (
    .A(PRDATA[4]),
    .B(read_data[4]),
    .S(_010_),
    .Z(_006_[4])
  );
  MUX2_X1 _070_ (
    .A(PRDATA[3]),
    .B(read_data[3]),
    .S(_010_),
    .Z(_006_[3])
  );
  MUX2_X1 _071_ (
    .A(PRDATA[2]),
    .B(read_data[2]),
    .S(_010_),
    .Z(_006_[2])
  );
  MUX2_X1 _072_ (
    .A(PRDATA[1]),
    .B(read_data[1]),
    .S(_010_),
    .Z(_006_[1])
  );
  MUX2_X1 _073_ (
    .A(PRDATA[0]),
    .B(read_data[0]),
    .S(_010_),
    .Z(_006_[0])
  );
  AOI21_X1 _074_ (
    .A(_007_),
    .B1(_023_),
    .B2(state[1]),
    .ZN(_002_)
  );
  AOI21_X1 _075_ (
    .A(_021_),
    .B1(_024_),
    .B2(state[0]),
    .ZN(_001_)
  );
  MUX2_X1 _076_ (
    .A(write_addr[6]),
    .B(read_addr[6]),
    .S(READ_WRITE),
    .Z(_011_)
  );
  MUX2_X1 _077_ (
    .A(PADDR[6]),
    .B(_011_),
    .S(_009_),
    .Z(_000_[6])
  );
  MUX2_X1 _078_ (
    .A(write_addr[5]),
    .B(read_addr[5]),
    .S(READ_WRITE),
    .Z(_012_)
  );
  MUX2_X1 _079_ (
    .A(PADDR[5]),
    .B(_012_),
    .S(_009_),
    .Z(_000_[5])
  );
  MUX2_X1 _080_ (
    .A(write_addr[4]),
    .B(read_addr[4]),
    .S(READ_WRITE),
    .Z(_013_)
  );
  MUX2_X1 _081_ (
    .A(PADDR[4]),
    .B(_013_),
    .S(_009_),
    .Z(_000_[4])
  );
  MUX2_X1 _082_ (
    .A(write_addr[3]),
    .B(read_addr[3]),
    .S(READ_WRITE),
    .Z(_014_)
  );
  MUX2_X1 _083_ (
    .A(PADDR[3]),
    .B(_014_),
    .S(_009_),
    .Z(_000_[3])
  );
  MUX2_X1 _084_ (
    .A(write_addr[2]),
    .B(read_addr[2]),
    .S(READ_WRITE),
    .Z(_015_)
  );
  MUX2_X1 _085_ (
    .A(PADDR[2]),
    .B(_015_),
    .S(_009_),
    .Z(_000_[2])
  );
  MUX2_X1 _086_ (
    .A(write_addr[1]),
    .B(read_addr[1]),
    .S(READ_WRITE),
    .Z(_016_)
  );
  MUX2_X1 _087_ (
    .A(PADDR[1]),
    .B(_016_),
    .S(_009_),
    .Z(_000_[1])
  );
  MUX2_X1 _088_ (
    .A(write_addr[0]),
    .B(read_addr[0]),
    .S(READ_WRITE),
    .Z(_017_)
  );
  MUX2_X1 _089_ (
    .A(PADDR[0]),
    .B(_017_),
    .S(_009_),
    .Z(_000_[0])
  );
  NOR3_X1 _090_ (
    .A1(_020_),
    .A2(state[1]),
    .A3(READ_WRITE),
    .ZN(_018_)
  );
  MUX2_X1 _091_ (
    .A(PWDATA[6]),
    .B(write_data[6]),
    .S(_018_),
    .Z(_003_[6])
  );
  MUX2_X1 _092_ (
    .A(PWDATA[5]),
    .B(write_data[5]),
    .S(_018_),
    .Z(_003_[5])
  );
  MUX2_X1 _093_ (
    .A(PWDATA[4]),
    .B(write_data[4]),
    .S(_018_),
    .Z(_003_[4])
  );
  MUX2_X1 _094_ (
    .A(PWDATA[3]),
    .B(write_data[3]),
    .S(_018_),
    .Z(_003_[3])
  );
  MUX2_X1 _095_ (
    .A(PWDATA[2]),
    .B(write_data[2]),
    .S(_018_),
    .Z(_003_[2])
  );
  MUX2_X1 _096_ (
    .A(PWDATA[1]),
    .B(write_data[1]),
    .S(_018_),
    .Z(_003_[1])
  );
  MUX2_X1 _097_ (
    .A(PWDATA[0]),
    .B(write_data[0]),
    .S(_018_),
    .Z(_003_[0])
  );
  MUX2_X1 _098_ (
    .A(PWDATA[7]),
    .B(write_data[7]),
    .S(_018_),
    .Z(_003_[7])
  );
  MUX2_X1 _099_ (
    .A(write_addr[7]),
    .B(read_addr[7]),
    .S(READ_WRITE),
    .Z(_019_)
  );
  MUX2_X1 _100_ (
    .A(PADDR[7]),
    .B(_019_),
    .S(_009_),
    .Z(_000_[7])
  );
  MUX2_X1 _101_ (
    .A(_022_),
    .B(PWRITE),
    .S(_008_),
    .Z(_004_)
  );
  MUX2_X1 _102_ (
    .A(PRDATA[7]),
    .B(read_data[7]),
    .S(_010_),
    .Z(_006_[7])
  );
  DFFR_X1 _103_ (
    .CK(PCLK),
    .D(_006_[0]),
    .Q(read_data[0]),
    .QN(_046_),
    .RN(PRESETn)
  );
  DFFR_X1 _104_ (
    .CK(PCLK),
    .D(_006_[1]),
    .Q(read_data[1]),
    .QN(_045_),
    .RN(PRESETn)
  );
  DFFR_X1 _105_ (
    .CK(PCLK),
    .D(_006_[2]),
    .Q(read_data[2]),
    .QN(_044_),
    .RN(PRESETn)
  );
  DFFR_X1 _106_ (
    .CK(PCLK),
    .D(_006_[3]),
    .Q(read_data[3]),
    .QN(_043_),
    .RN(PRESETn)
  );
  DFFR_X1 _107_ (
    .CK(PCLK),
    .D(_006_[4]),
    .Q(read_data[4]),
    .QN(_042_),
    .RN(PRESETn)
  );
  DFFR_X1 _108_ (
    .CK(PCLK),
    .D(_006_[5]),
    .Q(read_data[5]),
    .QN(_041_),
    .RN(PRESETn)
  );
  DFFR_X1 _109_ (
    .CK(PCLK),
    .D(_006_[6]),
    .Q(read_data[6]),
    .QN(_040_),
    .RN(PRESETn)
  );
  DFFR_X1 _110_ (
    .CK(PCLK),
    .D(_006_[7]),
    .Q(read_data[7]),
    .QN(_047_),
    .RN(PRESETn)
  );
  DFFR_X1 _111_ (
    .CK(PCLK),
    .D(_005_),
    .Q(done),
    .QN(_048_),
    .RN(PRESETn)
  );
  DFFR_X1 _112_ (
    .CK(PCLK),
    .D(_004_),
    .Q(PWRITE),
    .QN(_049_),
    .RN(PRESETn)
  );
  DFFR_X1 _113_ (
    .CK(PCLK),
    .D(_002_),
    .Q(PSEL),
    .QN(_050_),
    .RN(PRESETn)
  );
  DFFR_X1 _114_ (
    .CK(PCLK),
    .D(_001_),
    .Q(PENABLE),
    .QN(_051_),
    .RN(PRESETn)
  );
  DFFR_X1 _115_ (
    .CK(PCLK),
    .D(_000_[0]),
    .Q(PADDR[0]),
    .QN(_039_),
    .RN(PRESETn)
  );
  DFFR_X1 _116_ (
    .CK(PCLK),
    .D(_000_[1]),
    .Q(PADDR[1]),
    .QN(_038_),
    .RN(PRESETn)
  );
  DFFR_X1 _117_ (
    .CK(PCLK),
    .D(_000_[2]),
    .Q(PADDR[2]),
    .QN(_037_),
    .RN(PRESETn)
  );
  DFFR_X1 _118_ (
    .CK(PCLK),
    .D(_000_[3]),
    .Q(PADDR[3]),
    .QN(_036_),
    .RN(PRESETn)
  );
  DFFR_X1 _119_ (
    .CK(PCLK),
    .D(_000_[4]),
    .Q(PADDR[4]),
    .QN(_035_),
    .RN(PRESETn)
  );
  DFFR_X1 _120_ (
    .CK(PCLK),
    .D(_000_[5]),
    .Q(PADDR[5]),
    .QN(_034_),
    .RN(PRESETn)
  );
  DFFR_X1 _121_ (
    .CK(PCLK),
    .D(_000_[6]),
    .Q(PADDR[6]),
    .QN(_033_),
    .RN(PRESETn)
  );
  DFFR_X1 _122_ (
    .CK(PCLK),
    .D(_000_[7]),
    .Q(PADDR[7]),
    .QN(_052_),
    .RN(PRESETn)
  );
  DFFR_X1 _123_ (
    .CK(PCLK),
    .D(_003_[0]),
    .Q(PWDATA[0]),
    .QN(_032_),
    .RN(PRESETn)
  );
  DFFR_X1 _124_ (
    .CK(PCLK),
    .D(_003_[1]),
    .Q(PWDATA[1]),
    .QN(_031_),
    .RN(PRESETn)
  );
  DFFR_X1 _125_ (
    .CK(PCLK),
    .D(_003_[2]),
    .Q(PWDATA[2]),
    .QN(_030_),
    .RN(PRESETn)
  );
  DFFR_X1 _126_ (
    .CK(PCLK),
    .D(_003_[3]),
    .Q(PWDATA[3]),
    .QN(_029_),
    .RN(PRESETn)
  );
  DFFR_X1 _127_ (
    .CK(PCLK),
    .D(_003_[4]),
    .Q(PWDATA[4]),
    .QN(_028_),
    .RN(PRESETn)
  );
  DFFR_X1 _128_ (
    .CK(PCLK),
    .D(_003_[5]),
    .Q(PWDATA[5]),
    .QN(_027_),
    .RN(PRESETn)
  );
  DFFR_X1 _129_ (
    .CK(PCLK),
    .D(_003_[6]),
    .Q(PWDATA[6]),
    .QN(_026_),
    .RN(PRESETn)
  );
  DFFR_X1 _130_ (
    .CK(PCLK),
    .D(_003_[7]),
    .Q(PWDATA[7]),
    .QN(_053_),
    .RN(PRESETn)
  );
  DFFR_X1 _131_ (
    .CK(PCLK),
    .D(next_state[0]),
    .Q(state[0]),
    .QN(_025_),
    .RN(PRESETn)
  );
  DFFR_X1 _132_ (
    .CK(PCLK),
    .D(next_state[1]),
    .Q(state[1]),
    .QN(_054_),
    .RN(PRESETn)
  );
endmodule

module apb_slave(PCLK, PRESETn, PSEL, PENABLE, PWRITE, PADDR, PWDATA, PRDATA, PREADY);
  wire [7:0] _000_;
  wire _001_;
  wire [7:0] _002_;
  wire [7:0] _003_;
  wire [7:0] _004_;
  wire [7:0] _005_;
  wire [7:0] _006_;
  wire [7:0] _007_;
  wire [7:0] _008_;
  wire [7:0] _009_;
  wire [7:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  input [7:0] PADDR;
  input PCLK;
  input PENABLE;
  output [7:0] PRDATA;
  output PREADY;
  input PRESETn;
  input PSEL;
  input [7:0] PWDATA;
  input PWRITE;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [1:0] next_state;
  wire [1:0] state;
  INV_X1 _189_ (
    .A(\mem[8] [2]),
    .ZN(_011_)
  );
  INV_X1 _190_ (
    .A(state[0]),
    .ZN(_012_)
  );
  INV_X1 _191_ (
    .A(state[1]),
    .ZN(_013_)
  );
  INV_X1 _192_ (
    .A(PREADY),
    .ZN(_014_)
  );
  INV_X1 _193_ (
    .A(PADDR[2]),
    .ZN(_015_)
  );
  INV_X1 _194_ (
    .A(PADDR[1]),
    .ZN(_016_)
  );
  INV_X1 _195_ (
    .A(PADDR[0]),
    .ZN(_017_)
  );
  INV_X1 _196_ (
    .A(PADDR[3]),
    .ZN(_018_)
  );
  INV_X1 _197_ (
    .A(\mem[8] [7]),
    .ZN(_019_)
  );
  AND2_X1 _198_ (
    .A1(PSEL),
    .A2(PENABLE),
    .ZN(_020_)
  );
  AOI21_X1 _199_ (
    .A(state[0]),
    .B1(_013_),
    .B2(PSEL),
    .ZN(_021_)
  );
  AOI21_X1 _200_ (
    .A(_021_),
    .B1(_020_),
    .B2(_013_),
    .ZN(next_state[0])
  );
  NOR2_X1 _201_ (
    .A1(state[1]),
    .A2(_020_),
    .ZN(_022_)
  );
  NOR2_X1 _202_ (
    .A1(_012_),
    .A2(_022_),
    .ZN(next_state[1])
  );
  NOR2_X1 _203_ (
    .A1(PADDR[2]),
    .A2(PADDR[3]),
    .ZN(_023_)
  );
  AND3_X1 _204_ (
    .A1(_016_),
    .A2(PADDR[0]),
    .A3(_023_),
    .ZN(_024_)
  );
  NOR4_X1 _205_ (
    .A1(_015_),
    .A2(PADDR[1]),
    .A3(_017_),
    .A4(PADDR[3]),
    .ZN(_025_)
  );
  NOR2_X1 _206_ (
    .A1(PADDR[1]),
    .A2(PADDR[0]),
    .ZN(_026_)
  );
  NOR4_X1 _207_ (
    .A1(PADDR[2]),
    .A2(PADDR[1]),
    .A3(PADDR[0]),
    .A4(PADDR[3]),
    .ZN(_027_)
  );
  AND3_X1 _208_ (
    .A1(PADDR[2]),
    .A2(_018_),
    .A3(_026_),
    .ZN(_028_)
  );
  NAND3_X1 _209_ (
    .A1(PADDR[2]),
    .A2(_018_),
    .A3(_026_),
    .ZN(_029_)
  );
  AND3_X1 _210_ (
    .A1(PADDR[1]),
    .A2(_017_),
    .A3(_023_),
    .ZN(_030_)
  );
  NOR2_X1 _211_ (
    .A1(state[0]),
    .A2(_013_),
    .ZN(_031_)
  );
  NOR3_X1 _212_ (
    .A1(state[0]),
    .A2(_013_),
    .A3(PWRITE),
    .ZN(_032_)
  );
  NAND3_X1 _213_ (
    .A1(_015_),
    .A2(PADDR[3]),
    .A3(_026_),
    .ZN(_033_)
  );
  NAND4_X1 _214_ (
    .A1(\mem[8] [6]),
    .A2(_015_),
    .A3(PADDR[3]),
    .A4(_026_),
    .ZN(_034_)
  );
  AND2_X1 _215_ (
    .A1(PADDR[1]),
    .A2(PADDR[0]),
    .ZN(_035_)
  );
  AND2_X1 _216_ (
    .A1(_023_),
    .A2(_035_),
    .ZN(_036_)
  );
  NOR4_X1 _217_ (
    .A1(_015_),
    .A2(_016_),
    .A3(PADDR[0]),
    .A4(PADDR[3]),
    .ZN(_037_)
  );
  AND3_X1 _218_ (
    .A1(PADDR[2]),
    .A2(_018_),
    .A3(_035_),
    .ZN(_038_)
  );
  AOI22_X1 _219_ (
    .A1(\mem[1] [6]),
    .A2(_024_),
    .B1(_036_),
    .B2(\mem[3] [6]),
    .ZN(_039_)
  );
  AOI222_X1 _220_ (
    .A1(\mem[0] [6]),
    .A2(_027_),
    .B1(_030_),
    .B2(\mem[2] [6]),
    .C1(\mem[6] [6]),
    .C2(_037_),
    .ZN(_040_)
  );
  AND3_X1 _221_ (
    .A1(_034_),
    .A2(_039_),
    .A3(_040_),
    .ZN(_041_)
  );
  AOI222_X1 _222_ (
    .A1(\mem[5] [6]),
    .A2(_025_),
    .B1(_028_),
    .B2(\mem[4] [6]),
    .C1(_038_),
    .C2(\mem[7] [6]),
    .ZN(_042_)
  );
  AND2_X1 _223_ (
    .A1(_032_),
    .A2(_042_),
    .ZN(_043_)
  );
  NOR2_X1 _224_ (
    .A1(PRDATA[6]),
    .A2(_032_),
    .ZN(_044_)
  );
  AOI21_X1 _225_ (
    .A(_044_),
    .B1(_043_),
    .B2(_041_),
    .ZN(_000_[6])
  );
  NAND4_X1 _226_ (
    .A1(\mem[8] [5]),
    .A2(_015_),
    .A3(PADDR[3]),
    .A4(_026_),
    .ZN(_045_)
  );
  AOI22_X1 _227_ (
    .A1(\mem[1] [5]),
    .A2(_024_),
    .B1(_028_),
    .B2(\mem[4] [5]),
    .ZN(_046_)
  );
  AOI222_X1 _228_ (
    .A1(\mem[0] [5]),
    .A2(_027_),
    .B1(_037_),
    .B2(\mem[6] [5]),
    .C1(\mem[7] [5]),
    .C2(_038_),
    .ZN(_047_)
  );
  AND3_X1 _229_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_047_),
    .ZN(_048_)
  );
  AOI222_X1 _230_ (
    .A1(\mem[5] [5]),
    .A2(_025_),
    .B1(_030_),
    .B2(\mem[2] [5]),
    .C1(_036_),
    .C2(\mem[3] [5]),
    .ZN(_049_)
  );
  AND2_X1 _231_ (
    .A1(_032_),
    .A2(_049_),
    .ZN(_050_)
  );
  NOR2_X1 _232_ (
    .A1(PRDATA[5]),
    .A2(_032_),
    .ZN(_051_)
  );
  AOI21_X1 _233_ (
    .A(_051_),
    .B1(_050_),
    .B2(_048_),
    .ZN(_000_[5])
  );
  NAND4_X1 _234_ (
    .A1(\mem[8] [4]),
    .A2(_015_),
    .A3(PADDR[3]),
    .A4(_026_),
    .ZN(_052_)
  );
  AOI22_X1 _235_ (
    .A1(\mem[1] [4]),
    .A2(_024_),
    .B1(_038_),
    .B2(\mem[7] [4]),
    .ZN(_053_)
  );
  AOI222_X1 _236_ (
    .A1(\mem[4] [4]),
    .A2(_028_),
    .B1(_030_),
    .B2(\mem[2] [4]),
    .C1(_036_),
    .C2(\mem[3] [4]),
    .ZN(_054_)
  );
  AND3_X1 _237_ (
    .A1(_052_),
    .A2(_053_),
    .A3(_054_),
    .ZN(_055_)
  );
  AOI222_X1 _238_ (
    .A1(\mem[5] [4]),
    .A2(_025_),
    .B1(_027_),
    .B2(\mem[0] [4]),
    .C1(_037_),
    .C2(\mem[6] [4]),
    .ZN(_056_)
  );
  AND2_X1 _239_ (
    .A1(_032_),
    .A2(_056_),
    .ZN(_057_)
  );
  NOR2_X1 _240_ (
    .A1(PRDATA[4]),
    .A2(_032_),
    .ZN(_058_)
  );
  AOI21_X1 _241_ (
    .A(_058_),
    .B1(_057_),
    .B2(_055_),
    .ZN(_000_[4])
  );
  NAND4_X1 _242_ (
    .A1(\mem[8] [3]),
    .A2(_015_),
    .A3(PADDR[3]),
    .A4(_026_),
    .ZN(_059_)
  );
  AOI22_X1 _243_ (
    .A1(\mem[1] [3]),
    .A2(_024_),
    .B1(_036_),
    .B2(\mem[3] [3]),
    .ZN(_060_)
  );
  AOI222_X1 _244_ (
    .A1(\mem[0] [3]),
    .A2(_027_),
    .B1(_030_),
    .B2(\mem[2] [3]),
    .C1(\mem[6] [3]),
    .C2(_037_),
    .ZN(_061_)
  );
  AND3_X1 _245_ (
    .A1(_059_),
    .A2(_060_),
    .A3(_061_),
    .ZN(_062_)
  );
  AOI222_X1 _246_ (
    .A1(\mem[5] [3]),
    .A2(_025_),
    .B1(_028_),
    .B2(\mem[4] [3]),
    .C1(_038_),
    .C2(\mem[7] [3]),
    .ZN(_063_)
  );
  AND2_X1 _247_ (
    .A1(_032_),
    .A2(_063_),
    .ZN(_064_)
  );
  NOR2_X1 _248_ (
    .A1(PRDATA[3]),
    .A2(_032_),
    .ZN(_065_)
  );
  AOI21_X1 _249_ (
    .A(_065_),
    .B1(_064_),
    .B2(_062_),
    .ZN(_000_[3])
  );
  NAND3_X1 _250_ (
    .A1(\mem[3] [2]),
    .A2(_023_),
    .A3(_035_),
    .ZN(_066_)
  );
  OAI21_X1 _251_ (
    .A(_066_),
    .B1(_033_),
    .B2(_011_),
    .ZN(_067_)
  );
  AOI221_X1 _252_ (
    .A(_067_),
    .B1(_030_),
    .B2(\mem[2] [2]),
    .C1(\mem[6] [2]),
    .C2(_037_),
    .ZN(_068_)
  );
  NAND2_X1 _253_ (
    .A1(\mem[1] [2]),
    .A2(_024_),
    .ZN(_069_)
  );
  AOI22_X1 _254_ (
    .A1(\mem[4] [2]),
    .A2(_028_),
    .B1(_038_),
    .B2(\mem[7] [2]),
    .ZN(_070_)
  );
  AOI22_X1 _255_ (
    .A1(\mem[5] [2]),
    .A2(_025_),
    .B1(_027_),
    .B2(\mem[0] [2]),
    .ZN(_071_)
  );
  AND4_X1 _256_ (
    .A1(_032_),
    .A2(_069_),
    .A3(_070_),
    .A4(_071_),
    .ZN(_072_)
  );
  NOR2_X1 _257_ (
    .A1(PRDATA[2]),
    .A2(_032_),
    .ZN(_073_)
  );
  AOI21_X1 _258_ (
    .A(_073_),
    .B1(_072_),
    .B2(_068_),
    .ZN(_000_[2])
  );
  NAND4_X1 _259_ (
    .A1(\mem[8] [1]),
    .A2(_015_),
    .A3(PADDR[3]),
    .A4(_026_),
    .ZN(_074_)
  );
  AOI222_X1 _260_ (
    .A1(\mem[1] [1]),
    .A2(_024_),
    .B1(_025_),
    .B2(\mem[5] [1]),
    .C1(\mem[7] [1]),
    .C2(_038_),
    .ZN(_075_)
  );
  AOI222_X1 _261_ (
    .A1(\mem[4] [1]),
    .A2(_028_),
    .B1(_030_),
    .B2(\mem[2] [1]),
    .C1(_036_),
    .C2(\mem[3] [1]),
    .ZN(_076_)
  );
  AND2_X1 _262_ (
    .A1(_075_),
    .A2(_076_),
    .ZN(_077_)
  );
  AOI22_X1 _263_ (
    .A1(\mem[0] [1]),
    .A2(_027_),
    .B1(_037_),
    .B2(\mem[6] [1]),
    .ZN(_078_)
  );
  AND3_X1 _264_ (
    .A1(_032_),
    .A2(_074_),
    .A3(_078_),
    .ZN(_079_)
  );
  NOR2_X1 _265_ (
    .A1(PRDATA[1]),
    .A2(_032_),
    .ZN(_080_)
  );
  AOI21_X1 _266_ (
    .A(_080_),
    .B1(_079_),
    .B2(_077_),
    .ZN(_000_[1])
  );
  NAND4_X1 _267_ (
    .A1(\mem[8] [0]),
    .A2(_015_),
    .A3(PADDR[3]),
    .A4(_026_),
    .ZN(_081_)
  );
  AOI22_X1 _268_ (
    .A1(\mem[2] [0]),
    .A2(_030_),
    .B1(_038_),
    .B2(\mem[7] [0]),
    .ZN(_082_)
  );
  AOI222_X1 _269_ (
    .A1(\mem[4] [0]),
    .A2(_028_),
    .B1(_036_),
    .B2(\mem[3] [0]),
    .C1(\mem[1] [0]),
    .C2(_024_),
    .ZN(_083_)
  );
  AND3_X1 _270_ (
    .A1(_081_),
    .A2(_082_),
    .A3(_083_),
    .ZN(_084_)
  );
  AOI222_X1 _271_ (
    .A1(\mem[5] [0]),
    .A2(_025_),
    .B1(_027_),
    .B2(\mem[0] [0]),
    .C1(_037_),
    .C2(\mem[6] [0]),
    .ZN(_085_)
  );
  AND2_X1 _272_ (
    .A1(_032_),
    .A2(_085_),
    .ZN(_086_)
  );
  NOR2_X1 _273_ (
    .A1(PRDATA[0]),
    .A2(_032_),
    .ZN(_087_)
  );
  AOI21_X1 _274_ (
    .A(_087_),
    .B1(_086_),
    .B2(_084_),
    .ZN(_000_[0])
  );
  AOI21_X1 _275_ (
    .A(_013_),
    .B1(_014_),
    .B2(state[0]),
    .ZN(_001_)
  );
  NAND2_X1 _276_ (
    .A1(PWRITE),
    .A2(_031_),
    .ZN(_088_)
  );
  AND3_X1 _277_ (
    .A1(PWRITE),
    .A2(_031_),
    .A3(_036_),
    .ZN(_089_)
  );
  MUX2_X1 _278_ (
    .A(\mem[3] [6]),
    .B(PWDATA[6]),
    .S(_089_),
    .Z(_005_[6])
  );
  MUX2_X1 _279_ (
    .A(\mem[3] [5]),
    .B(PWDATA[5]),
    .S(_089_),
    .Z(_005_[5])
  );
  MUX2_X1 _280_ (
    .A(\mem[3] [4]),
    .B(PWDATA[4]),
    .S(_089_),
    .Z(_005_[4])
  );
  MUX2_X1 _281_ (
    .A(\mem[3] [3]),
    .B(PWDATA[3]),
    .S(_089_),
    .Z(_005_[3])
  );
  MUX2_X1 _282_ (
    .A(\mem[3] [2]),
    .B(PWDATA[2]),
    .S(_089_),
    .Z(_005_[2])
  );
  MUX2_X1 _283_ (
    .A(\mem[3] [1]),
    .B(PWDATA[1]),
    .S(_089_),
    .Z(_005_[1])
  );
  MUX2_X1 _284_ (
    .A(\mem[3] [0]),
    .B(PWDATA[0]),
    .S(_089_),
    .Z(_005_[0])
  );
  NOR2_X1 _285_ (
    .A1(_029_),
    .A2(_088_),
    .ZN(_090_)
  );
  MUX2_X1 _286_ (
    .A(\mem[4] [6]),
    .B(PWDATA[6]),
    .S(_090_),
    .Z(_006_[6])
  );
  MUX2_X1 _287_ (
    .A(\mem[4] [5]),
    .B(PWDATA[5]),
    .S(_090_),
    .Z(_006_[5])
  );
  MUX2_X1 _288_ (
    .A(\mem[4] [4]),
    .B(PWDATA[4]),
    .S(_090_),
    .Z(_006_[4])
  );
  MUX2_X1 _289_ (
    .A(\mem[4] [3]),
    .B(PWDATA[3]),
    .S(_090_),
    .Z(_006_[3])
  );
  MUX2_X1 _290_ (
    .A(\mem[4] [2]),
    .B(PWDATA[2]),
    .S(_090_),
    .Z(_006_[2])
  );
  MUX2_X1 _291_ (
    .A(\mem[4] [1]),
    .B(PWDATA[1]),
    .S(_090_),
    .Z(_006_[1])
  );
  MUX2_X1 _292_ (
    .A(\mem[4] [0]),
    .B(PWDATA[0]),
    .S(_090_),
    .Z(_006_[0])
  );
  AND3_X1 _293_ (
    .A1(PWRITE),
    .A2(_025_),
    .A3(_031_),
    .ZN(_091_)
  );
  MUX2_X1 _294_ (
    .A(\mem[5] [6]),
    .B(PWDATA[6]),
    .S(_091_),
    .Z(_007_[6])
  );
  MUX2_X1 _295_ (
    .A(\mem[5] [5]),
    .B(PWDATA[5]),
    .S(_091_),
    .Z(_007_[5])
  );
  MUX2_X1 _296_ (
    .A(\mem[5] [4]),
    .B(PWDATA[4]),
    .S(_091_),
    .Z(_007_[4])
  );
  MUX2_X1 _297_ (
    .A(\mem[5] [3]),
    .B(PWDATA[3]),
    .S(_091_),
    .Z(_007_[3])
  );
  MUX2_X1 _298_ (
    .A(\mem[5] [2]),
    .B(PWDATA[2]),
    .S(_091_),
    .Z(_007_[2])
  );
  MUX2_X1 _299_ (
    .A(\mem[5] [1]),
    .B(PWDATA[1]),
    .S(_091_),
    .Z(_007_[1])
  );
  MUX2_X1 _300_ (
    .A(\mem[5] [0]),
    .B(PWDATA[0]),
    .S(_091_),
    .Z(_007_[0])
  );
  AND3_X1 _301_ (
    .A1(PWRITE),
    .A2(_024_),
    .A3(_031_),
    .ZN(_092_)
  );
  MUX2_X1 _302_ (
    .A(\mem[1] [6]),
    .B(PWDATA[6]),
    .S(_092_),
    .Z(_003_[6])
  );
  MUX2_X1 _303_ (
    .A(\mem[1] [5]),
    .B(PWDATA[5]),
    .S(_092_),
    .Z(_003_[5])
  );
  MUX2_X1 _304_ (
    .A(\mem[1] [4]),
    .B(PWDATA[4]),
    .S(_092_),
    .Z(_003_[4])
  );
  MUX2_X1 _305_ (
    .A(\mem[1] [3]),
    .B(PWDATA[3]),
    .S(_092_),
    .Z(_003_[3])
  );
  MUX2_X1 _306_ (
    .A(\mem[1] [2]),
    .B(PWDATA[2]),
    .S(_092_),
    .Z(_003_[2])
  );
  MUX2_X1 _307_ (
    .A(\mem[1] [1]),
    .B(PWDATA[1]),
    .S(_092_),
    .Z(_003_[1])
  );
  MUX2_X1 _308_ (
    .A(\mem[1] [0]),
    .B(PWDATA[0]),
    .S(_092_),
    .Z(_003_[0])
  );
  AND3_X1 _309_ (
    .A1(PWRITE),
    .A2(_031_),
    .A3(_038_),
    .ZN(_093_)
  );
  MUX2_X1 _310_ (
    .A(\mem[7] [6]),
    .B(PWDATA[6]),
    .S(_093_),
    .Z(_009_[6])
  );
  MUX2_X1 _311_ (
    .A(\mem[7] [5]),
    .B(PWDATA[5]),
    .S(_093_),
    .Z(_009_[5])
  );
  MUX2_X1 _312_ (
    .A(\mem[7] [4]),
    .B(PWDATA[4]),
    .S(_093_),
    .Z(_009_[4])
  );
  MUX2_X1 _313_ (
    .A(\mem[7] [3]),
    .B(PWDATA[3]),
    .S(_093_),
    .Z(_009_[3])
  );
  MUX2_X1 _314_ (
    .A(\mem[7] [2]),
    .B(PWDATA[2]),
    .S(_093_),
    .Z(_009_[2])
  );
  MUX2_X1 _315_ (
    .A(\mem[7] [1]),
    .B(PWDATA[1]),
    .S(_093_),
    .Z(_009_[1])
  );
  MUX2_X1 _316_ (
    .A(\mem[7] [0]),
    .B(PWDATA[0]),
    .S(_093_),
    .Z(_009_[0])
  );
  NOR2_X1 _317_ (
    .A1(_033_),
    .A2(_088_),
    .ZN(_094_)
  );
  MUX2_X1 _318_ (
    .A(\mem[8] [6]),
    .B(PWDATA[6]),
    .S(_094_),
    .Z(_010_[6])
  );
  MUX2_X1 _319_ (
    .A(\mem[8] [5]),
    .B(PWDATA[5]),
    .S(_094_),
    .Z(_010_[5])
  );
  MUX2_X1 _320_ (
    .A(\mem[8] [4]),
    .B(PWDATA[4]),
    .S(_094_),
    .Z(_010_[4])
  );
  MUX2_X1 _321_ (
    .A(\mem[8] [3]),
    .B(PWDATA[3]),
    .S(_094_),
    .Z(_010_[3])
  );
  MUX2_X1 _322_ (
    .A(\mem[8] [2]),
    .B(PWDATA[2]),
    .S(_094_),
    .Z(_010_[2])
  );
  MUX2_X1 _323_ (
    .A(\mem[8] [1]),
    .B(PWDATA[1]),
    .S(_094_),
    .Z(_010_[1])
  );
  MUX2_X1 _324_ (
    .A(\mem[8] [0]),
    .B(PWDATA[0]),
    .S(_094_),
    .Z(_010_[0])
  );
  NAND3_X1 _325_ (
    .A1(PWRITE),
    .A2(_027_),
    .A3(_031_),
    .ZN(_095_)
  );
  MUX2_X1 _326_ (
    .A(PWDATA[6]),
    .B(\mem[0] [6]),
    .S(_095_),
    .Z(_002_[6])
  );
  MUX2_X1 _327_ (
    .A(PWDATA[5]),
    .B(\mem[0] [5]),
    .S(_095_),
    .Z(_002_[5])
  );
  MUX2_X1 _328_ (
    .A(PWDATA[4]),
    .B(\mem[0] [4]),
    .S(_095_),
    .Z(_002_[4])
  );
  MUX2_X1 _329_ (
    .A(PWDATA[3]),
    .B(\mem[0] [3]),
    .S(_095_),
    .Z(_002_[3])
  );
  MUX2_X1 _330_ (
    .A(PWDATA[2]),
    .B(\mem[0] [2]),
    .S(_095_),
    .Z(_002_[2])
  );
  MUX2_X1 _331_ (
    .A(PWDATA[1]),
    .B(\mem[0] [1]),
    .S(_095_),
    .Z(_002_[1])
  );
  MUX2_X1 _332_ (
    .A(PWDATA[0]),
    .B(\mem[0] [0]),
    .S(_095_),
    .Z(_002_[0])
  );
  AND3_X1 _333_ (
    .A1(PWRITE),
    .A2(_030_),
    .A3(_031_),
    .ZN(_096_)
  );
  MUX2_X1 _334_ (
    .A(\mem[2] [6]),
    .B(PWDATA[6]),
    .S(_096_),
    .Z(_004_[6])
  );
  MUX2_X1 _335_ (
    .A(\mem[2] [5]),
    .B(PWDATA[5]),
    .S(_096_),
    .Z(_004_[5])
  );
  MUX2_X1 _336_ (
    .A(\mem[2] [4]),
    .B(PWDATA[4]),
    .S(_096_),
    .Z(_004_[4])
  );
  MUX2_X1 _337_ (
    .A(\mem[2] [3]),
    .B(PWDATA[3]),
    .S(_096_),
    .Z(_004_[3])
  );
  MUX2_X1 _338_ (
    .A(\mem[2] [2]),
    .B(PWDATA[2]),
    .S(_096_),
    .Z(_004_[2])
  );
  MUX2_X1 _339_ (
    .A(\mem[2] [1]),
    .B(PWDATA[1]),
    .S(_096_),
    .Z(_004_[1])
  );
  MUX2_X1 _340_ (
    .A(\mem[2] [0]),
    .B(PWDATA[0]),
    .S(_096_),
    .Z(_004_[0])
  );
  AND3_X1 _341_ (
    .A1(PWRITE),
    .A2(_031_),
    .A3(_037_),
    .ZN(_097_)
  );
  MUX2_X1 _342_ (
    .A(\mem[6] [6]),
    .B(PWDATA[6]),
    .S(_097_),
    .Z(_008_[6])
  );
  MUX2_X1 _343_ (
    .A(\mem[6] [5]),
    .B(PWDATA[5]),
    .S(_097_),
    .Z(_008_[5])
  );
  MUX2_X1 _344_ (
    .A(\mem[6] [4]),
    .B(PWDATA[4]),
    .S(_097_),
    .Z(_008_[4])
  );
  MUX2_X1 _345_ (
    .A(\mem[6] [3]),
    .B(PWDATA[3]),
    .S(_097_),
    .Z(_008_[3])
  );
  MUX2_X1 _346_ (
    .A(\mem[6] [2]),
    .B(PWDATA[2]),
    .S(_097_),
    .Z(_008_[2])
  );
  MUX2_X1 _347_ (
    .A(\mem[6] [1]),
    .B(PWDATA[1]),
    .S(_097_),
    .Z(_008_[1])
  );
  MUX2_X1 _348_ (
    .A(\mem[6] [0]),
    .B(PWDATA[0]),
    .S(_097_),
    .Z(_008_[0])
  );
  MUX2_X1 _349_ (
    .A(\mem[2] [7]),
    .B(PWDATA[7]),
    .S(_096_),
    .Z(_004_[7])
  );
  MUX2_X1 _350_ (
    .A(PWDATA[7]),
    .B(\mem[0] [7]),
    .S(_095_),
    .Z(_002_[7])
  );
  MUX2_X1 _351_ (
    .A(\mem[8] [7]),
    .B(PWDATA[7]),
    .S(_094_),
    .Z(_010_[7])
  );
  MUX2_X1 _352_ (
    .A(\mem[7] [7]),
    .B(PWDATA[7]),
    .S(_093_),
    .Z(_009_[7])
  );
  MUX2_X1 _353_ (
    .A(\mem[1] [7]),
    .B(PWDATA[7]),
    .S(_092_),
    .Z(_003_[7])
  );
  MUX2_X1 _354_ (
    .A(\mem[5] [7]),
    .B(PWDATA[7]),
    .S(_091_),
    .Z(_007_[7])
  );
  MUX2_X1 _355_ (
    .A(\mem[4] [7]),
    .B(PWDATA[7]),
    .S(_090_),
    .Z(_006_[7])
  );
  MUX2_X1 _356_ (
    .A(\mem[3] [7]),
    .B(PWDATA[7]),
    .S(_089_),
    .Z(_005_[7])
  );
  NAND2_X1 _357_ (
    .A1(\mem[0] [7]),
    .A2(_027_),
    .ZN(_098_)
  );
  OAI21_X1 _358_ (
    .A(_098_),
    .B1(_033_),
    .B2(_019_),
    .ZN(_099_)
  );
  AOI221_X1 _359_ (
    .A(_099_),
    .B1(_028_),
    .B2(\mem[4] [7]),
    .C1(\mem[6] [7]),
    .C2(_037_),
    .ZN(_100_)
  );
  NAND2_X1 _360_ (
    .A1(\mem[2] [7]),
    .A2(_030_),
    .ZN(_101_)
  );
  AOI22_X1 _361_ (
    .A1(\mem[1] [7]),
    .A2(_024_),
    .B1(_038_),
    .B2(\mem[7] [7]),
    .ZN(_102_)
  );
  AOI22_X1 _362_ (
    .A1(\mem[5] [7]),
    .A2(_025_),
    .B1(_036_),
    .B2(\mem[3] [7]),
    .ZN(_103_)
  );
  AND4_X1 _363_ (
    .A1(_032_),
    .A2(_101_),
    .A3(_102_),
    .A4(_103_),
    .ZN(_104_)
  );
  NOR2_X1 _364_ (
    .A1(PRDATA[7]),
    .A2(_032_),
    .ZN(_105_)
  );
  AOI21_X1 _365_ (
    .A(_105_),
    .B1(_104_),
    .B2(_100_),
    .ZN(_000_[7])
  );
  MUX2_X1 _366_ (
    .A(\mem[6] [7]),
    .B(PWDATA[7]),
    .S(_097_),
    .Z(_008_[7])
  );
  DFF_X1 _367_ (
    .CK(PCLK),
    .D(_005_[0]),
    .Q(\mem[3] [0]),
    .QN(_169_)
  );
  DFF_X1 _368_ (
    .CK(PCLK),
    .D(_005_[1]),
    .Q(\mem[3] [1]),
    .QN(_168_)
  );
  DFF_X1 _369_ (
    .CK(PCLK),
    .D(_005_[2]),
    .Q(\mem[3] [2]),
    .QN(_167_)
  );
  DFF_X1 _370_ (
    .CK(PCLK),
    .D(_005_[3]),
    .Q(\mem[3] [3]),
    .QN(_166_)
  );
  DFF_X1 _371_ (
    .CK(PCLK),
    .D(_005_[4]),
    .Q(\mem[3] [4]),
    .QN(_165_)
  );
  DFF_X1 _372_ (
    .CK(PCLK),
    .D(_005_[5]),
    .Q(\mem[3] [5]),
    .QN(_164_)
  );
  DFF_X1 _373_ (
    .CK(PCLK),
    .D(_005_[6]),
    .Q(\mem[3] [6]),
    .QN(_163_)
  );
  DFF_X1 _374_ (
    .CK(PCLK),
    .D(_005_[7]),
    .Q(\mem[3] [7]),
    .QN(_179_)
  );
  DFF_X1 _375_ (
    .CK(PCLK),
    .D(_006_[0]),
    .Q(\mem[4] [0]),
    .QN(_162_)
  );
  DFF_X1 _376_ (
    .CK(PCLK),
    .D(_006_[1]),
    .Q(\mem[4] [1]),
    .QN(_161_)
  );
  DFF_X1 _377_ (
    .CK(PCLK),
    .D(_006_[2]),
    .Q(\mem[4] [2]),
    .QN(_160_)
  );
  DFF_X1 _378_ (
    .CK(PCLK),
    .D(_006_[3]),
    .Q(\mem[4] [3]),
    .QN(_159_)
  );
  DFF_X1 _379_ (
    .CK(PCLK),
    .D(_006_[4]),
    .Q(\mem[4] [4]),
    .QN(_158_)
  );
  DFF_X1 _380_ (
    .CK(PCLK),
    .D(_006_[5]),
    .Q(\mem[4] [5]),
    .QN(_157_)
  );
  DFF_X1 _381_ (
    .CK(PCLK),
    .D(_006_[6]),
    .Q(\mem[4] [6]),
    .QN(_156_)
  );
  DFF_X1 _382_ (
    .CK(PCLK),
    .D(_006_[7]),
    .Q(\mem[4] [7]),
    .QN(_180_)
  );
  DFF_X1 _383_ (
    .CK(PCLK),
    .D(_007_[0]),
    .Q(\mem[5] [0]),
    .QN(_155_)
  );
  DFF_X1 _384_ (
    .CK(PCLK),
    .D(_007_[1]),
    .Q(\mem[5] [1]),
    .QN(_154_)
  );
  DFF_X1 _385_ (
    .CK(PCLK),
    .D(_007_[2]),
    .Q(\mem[5] [2]),
    .QN(_153_)
  );
  DFF_X1 _386_ (
    .CK(PCLK),
    .D(_007_[3]),
    .Q(\mem[5] [3]),
    .QN(_152_)
  );
  DFF_X1 _387_ (
    .CK(PCLK),
    .D(_007_[4]),
    .Q(\mem[5] [4]),
    .QN(_151_)
  );
  DFF_X1 _388_ (
    .CK(PCLK),
    .D(_007_[5]),
    .Q(\mem[5] [5]),
    .QN(_150_)
  );
  DFF_X1 _389_ (
    .CK(PCLK),
    .D(_007_[6]),
    .Q(\mem[5] [6]),
    .QN(_149_)
  );
  DFF_X1 _390_ (
    .CK(PCLK),
    .D(_007_[7]),
    .Q(\mem[5] [7]),
    .QN(_181_)
  );
  DFF_X1 _391_ (
    .CK(PCLK),
    .D(_003_[0]),
    .Q(\mem[1] [0]),
    .QN(_148_)
  );
  DFF_X1 _392_ (
    .CK(PCLK),
    .D(_003_[1]),
    .Q(\mem[1] [1]),
    .QN(_147_)
  );
  DFF_X1 _393_ (
    .CK(PCLK),
    .D(_003_[2]),
    .Q(\mem[1] [2]),
    .QN(_146_)
  );
  DFF_X1 _394_ (
    .CK(PCLK),
    .D(_003_[3]),
    .Q(\mem[1] [3]),
    .QN(_145_)
  );
  DFF_X1 _395_ (
    .CK(PCLK),
    .D(_003_[4]),
    .Q(\mem[1] [4]),
    .QN(_144_)
  );
  DFF_X1 _396_ (
    .CK(PCLK),
    .D(_003_[5]),
    .Q(\mem[1] [5]),
    .QN(_143_)
  );
  DFF_X1 _397_ (
    .CK(PCLK),
    .D(_003_[6]),
    .Q(\mem[1] [6]),
    .QN(_142_)
  );
  DFF_X1 _398_ (
    .CK(PCLK),
    .D(_003_[7]),
    .Q(\mem[1] [7]),
    .QN(_182_)
  );
  DFF_X1 _399_ (
    .CK(PCLK),
    .D(_009_[0]),
    .Q(\mem[7] [0]),
    .QN(_141_)
  );
  DFF_X1 _400_ (
    .CK(PCLK),
    .D(_009_[1]),
    .Q(\mem[7] [1]),
    .QN(_140_)
  );
  DFF_X1 _401_ (
    .CK(PCLK),
    .D(_009_[2]),
    .Q(\mem[7] [2]),
    .QN(_139_)
  );
  DFF_X1 _402_ (
    .CK(PCLK),
    .D(_009_[3]),
    .Q(\mem[7] [3]),
    .QN(_138_)
  );
  DFF_X1 _403_ (
    .CK(PCLK),
    .D(_009_[4]),
    .Q(\mem[7] [4]),
    .QN(_137_)
  );
  DFF_X1 _404_ (
    .CK(PCLK),
    .D(_009_[5]),
    .Q(\mem[7] [5]),
    .QN(_136_)
  );
  DFF_X1 _405_ (
    .CK(PCLK),
    .D(_009_[6]),
    .Q(\mem[7] [6]),
    .QN(_135_)
  );
  DFF_X1 _406_ (
    .CK(PCLK),
    .D(_009_[7]),
    .Q(\mem[7] [7]),
    .QN(_183_)
  );
  DFF_X1 _407_ (
    .CK(PCLK),
    .D(_010_[0]),
    .Q(\mem[8] [0]),
    .QN(_134_)
  );
  DFF_X1 _408_ (
    .CK(PCLK),
    .D(_010_[1]),
    .Q(\mem[8] [1]),
    .QN(_133_)
  );
  DFF_X1 _409_ (
    .CK(PCLK),
    .D(_010_[2]),
    .Q(\mem[8] [2]),
    .QN(_132_)
  );
  DFF_X1 _410_ (
    .CK(PCLK),
    .D(_010_[3]),
    .Q(\mem[8] [3]),
    .QN(_131_)
  );
  DFF_X1 _411_ (
    .CK(PCLK),
    .D(_010_[4]),
    .Q(\mem[8] [4]),
    .QN(_130_)
  );
  DFF_X1 _412_ (
    .CK(PCLK),
    .D(_010_[5]),
    .Q(\mem[8] [5]),
    .QN(_129_)
  );
  DFF_X1 _413_ (
    .CK(PCLK),
    .D(_010_[6]),
    .Q(\mem[8] [6]),
    .QN(_128_)
  );
  DFF_X1 _414_ (
    .CK(PCLK),
    .D(_010_[7]),
    .Q(\mem[8] [7]),
    .QN(_184_)
  );
  DFF_X1 _415_ (
    .CK(PCLK),
    .D(_002_[0]),
    .Q(\mem[0] [0]),
    .QN(_127_)
  );
  DFF_X1 _416_ (
    .CK(PCLK),
    .D(_002_[1]),
    .Q(\mem[0] [1]),
    .QN(_126_)
  );
  DFF_X1 _417_ (
    .CK(PCLK),
    .D(_002_[2]),
    .Q(\mem[0] [2]),
    .QN(_125_)
  );
  DFF_X1 _418_ (
    .CK(PCLK),
    .D(_002_[3]),
    .Q(\mem[0] [3]),
    .QN(_124_)
  );
  DFF_X1 _419_ (
    .CK(PCLK),
    .D(_002_[4]),
    .Q(\mem[0] [4]),
    .QN(_123_)
  );
  DFF_X1 _420_ (
    .CK(PCLK),
    .D(_002_[5]),
    .Q(\mem[0] [5]),
    .QN(_122_)
  );
  DFF_X1 _421_ (
    .CK(PCLK),
    .D(_002_[6]),
    .Q(\mem[0] [6]),
    .QN(_121_)
  );
  DFF_X1 _422_ (
    .CK(PCLK),
    .D(_002_[7]),
    .Q(\mem[0] [7]),
    .QN(_185_)
  );
  DFF_X1 _423_ (
    .CK(PCLK),
    .D(_004_[0]),
    .Q(\mem[2] [0]),
    .QN(_120_)
  );
  DFF_X1 _424_ (
    .CK(PCLK),
    .D(_004_[1]),
    .Q(\mem[2] [1]),
    .QN(_119_)
  );
  DFF_X1 _425_ (
    .CK(PCLK),
    .D(_004_[2]),
    .Q(\mem[2] [2]),
    .QN(_118_)
  );
  DFF_X1 _426_ (
    .CK(PCLK),
    .D(_004_[3]),
    .Q(\mem[2] [3]),
    .QN(_117_)
  );
  DFF_X1 _427_ (
    .CK(PCLK),
    .D(_004_[4]),
    .Q(\mem[2] [4]),
    .QN(_116_)
  );
  DFF_X1 _428_ (
    .CK(PCLK),
    .D(_004_[5]),
    .Q(\mem[2] [5]),
    .QN(_115_)
  );
  DFF_X1 _429_ (
    .CK(PCLK),
    .D(_004_[6]),
    .Q(\mem[2] [6]),
    .QN(_114_)
  );
  DFF_X1 _430_ (
    .CK(PCLK),
    .D(_004_[7]),
    .Q(\mem[2] [7]),
    .QN(_186_)
  );
  DFF_X1 _431_ (
    .CK(PCLK),
    .D(_008_[0]),
    .Q(\mem[6] [0]),
    .QN(_113_)
  );
  DFF_X1 _432_ (
    .CK(PCLK),
    .D(_008_[1]),
    .Q(\mem[6] [1]),
    .QN(_112_)
  );
  DFF_X1 _433_ (
    .CK(PCLK),
    .D(_008_[2]),
    .Q(\mem[6] [2]),
    .QN(_111_)
  );
  DFF_X1 _434_ (
    .CK(PCLK),
    .D(_008_[3]),
    .Q(\mem[6] [3]),
    .QN(_110_)
  );
  DFF_X1 _435_ (
    .CK(PCLK),
    .D(_008_[4]),
    .Q(\mem[6] [4]),
    .QN(_109_)
  );
  DFF_X1 _436_ (
    .CK(PCLK),
    .D(_008_[5]),
    .Q(\mem[6] [5]),
    .QN(_108_)
  );
  DFF_X1 _437_ (
    .CK(PCLK),
    .D(_008_[6]),
    .Q(\mem[6] [6]),
    .QN(_107_)
  );
  DFF_X1 _438_ (
    .CK(PCLK),
    .D(_008_[7]),
    .Q(\mem[6] [7]),
    .QN(_187_)
  );
  DFFR_X1 _439_ (
    .CK(PCLK),
    .D(_000_[0]),
    .Q(PRDATA[0]),
    .QN(_176_),
    .RN(PRESETn)
  );
  DFFR_X1 _440_ (
    .CK(PCLK),
    .D(_000_[1]),
    .Q(PRDATA[1]),
    .QN(_175_),
    .RN(PRESETn)
  );
  DFFR_X1 _441_ (
    .CK(PCLK),
    .D(_000_[2]),
    .Q(PRDATA[2]),
    .QN(_174_),
    .RN(PRESETn)
  );
  DFFR_X1 _442_ (
    .CK(PCLK),
    .D(_000_[3]),
    .Q(PRDATA[3]),
    .QN(_173_),
    .RN(PRESETn)
  );
  DFFR_X1 _443_ (
    .CK(PCLK),
    .D(_000_[4]),
    .Q(PRDATA[4]),
    .QN(_172_),
    .RN(PRESETn)
  );
  DFFR_X1 _444_ (
    .CK(PCLK),
    .D(_000_[5]),
    .Q(PRDATA[5]),
    .QN(_171_),
    .RN(PRESETn)
  );
  DFFR_X1 _445_ (
    .CK(PCLK),
    .D(_000_[6]),
    .Q(PRDATA[6]),
    .QN(_170_),
    .RN(PRESETn)
  );
  DFFR_X1 _446_ (
    .CK(PCLK),
    .D(_000_[7]),
    .Q(PRDATA[7]),
    .QN(_177_),
    .RN(PRESETn)
  );
  DFFR_X1 _447_ (
    .CK(PCLK),
    .D(_001_),
    .Q(PREADY),
    .QN(_178_),
    .RN(PRESETn)
  );
  DFFR_X1 _448_ (
    .CK(PCLK),
    .D(next_state[0]),
    .Q(state[0]),
    .QN(_106_),
    .RN(PRESETn)
  );
  DFFR_X1 _449_ (
    .CK(PCLK),
    .D(next_state[1]),
    .Q(state[1]),
    .QN(_188_),
    .RN(PRESETn)
  );
endmodule
